### ISSUE TITLE
[Feature Request] Allow saving/sharing connection details

### ISSUE THREAD

**Issue by rhaces** [aws/graph-explorer#111]
**Community Note**
* Please use a 👍 reaction to provide a +1/vote. This helps the community and maintainers prioritize this request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Graph Explorer Version (and Graph Database and Version used if applicable)**
Any

**Is your feature request related to a problem? Please describe.**
Enhancement

**Describe the solution you'd like**
I want to have the ability to save the connection details server side, or in a shareable method, so that other members of the organization can access graph explorer and connect to the same database without needing to configure the connection again

**Additional context**

**Comment by jackson-millard** [comment]
If you are on the connections page and click on a previously created connection, there should be a downward pointing arrow icon that is for exporting the connection. If you hover over it, you should see "Export Connection". Conversely, in the "Available connections" panel, you should see an upward pointing arrow that is for importing the file that you exported via the export button. 

If you want to store these files, you'll need to export the connection and manually place it in some storage system and then the next user will need to import it themselves.

**Comment by paulduttonpad** [comment]
This function seems to work on a single users browser, but trying with another user/browser, the import seems to only bring in the connection details and not the styling as described.

I have a workaround to hack out the database to JSON (via console) and then import on a new machine, however this would be much better if the connection export and import would work across browsers/sessions/PCs

To test, export a connection with styles, then try to import into a incognito session and you will see that only the connection is imported and none of the styling.

**Comment by kmcginnes** [comment]
## Closing Summary

I'm closing this issue because the original feature request exists within the app already.

1. Open Graph Explorer to the Connections screen
2. Choose the connection you want to share
3. Click the "Export Connection" button in the connection details, 
  a. This will save the connection as a file in your system

You can share that file with whomever has permissions to access the database in question. In their browser you will import that file.

1. Open Graph Explorer to the Connections screen
2. Click the "Import Connection" button at the top of the connection list
3. Choose the file you exported from the steps above

The connection will be created and a schema sync will be automatically started. Once complete the connection is available for use.

### Other Comments

There were a few comments about sharing style config to multiple users. There are a few existing feature requests for this.

- #112 
- #298

There was also a mention of copying the entire local database and restoring it to another browser. This is a feature added to Graph Explorer v1.10.

- #549

One caveat is that the restore process will replace all existing config data. So it is best used for initial setup, not continuous sharing.
